window.BARRIER_DATABASE = {
  "metadata": {
    "source_file": "Barrier data.xlsx",
    "instruction": "This JSON file contains the exact data values extracted from the source Excel file organized by sheet name."
  },
  "data": {
    "Barrier data": [
      [
        "Barrier System",
        "Barrier System",
        "Accepted Test Level",
        "Type",
        "Anchor/Post Spacing (m) ",
        "Post/Pin Type ",
        "TMR Conditions (Speed)",
        "Test Speed (km/h)",
        "Width of barrier",
        "Tested Article Length (m) ",
        "Deflection (m)",
        "Working Width (m)",
        "Side slope limit ",
        "Available Lengths (m)",
        "Unit Weight (kg)",
        "Registered Supplier",
        "Austroads TCU Link",
        null,
        "Manufacturers Specifications",
        "Image Link",
        "TMR Conditions",
        null
      ],
      [
        "Precast Concrete Barrier (PCB)",
        "Precast Concrete Barrier (PCB)",
        "Not Rated",
        "Concrete Single Slope",
        null,
        null,
        "Refer to Appendix B",
        "N/A",
        null,
        null,
        "N/A",
        "N/A",
        null,
        null,
        null,
        "Public Domain",
        "Public Domain ",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "DB80 K150",
        "DB80 K150 Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Freestanding",
        "NA",
        "Max 80 km/h",
        100,
        0.57,
        61.17,
        1.44,
        1.94,
        0.07,
        "2,4,6",
        "1200/ 2400 / 3600",
        "Jaybro Group Pty Ltd",
        "Austroads TCU - DB80 K150",
        "https://austroads.gov.au/__data/assets/pdf_file/0018/433206/210720-TCU-DB80-K150-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDX7trjrgYoSJsV4jJPnx4PAbdOzJasBl5HFtl9VxgNDE4?e=G5cE0F",
        "https://cromptonconcepts-my.sharepoint.com/:i:/g/personal/sanju_cromptonconcepts_com_au/IQDB3nHWBlTIT6IczRFGLHBsAQsQh4aUQgZKefFvFc3Mh9E?e=Aci4p5",
        "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        "DB80 T150S",
        "DB80 T150S Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Anchored at ends only",
        "NA",
        "Max 80 km/h",
        100,
        0.57,
        92,
        0.81,
        1.36,
        0.1,
        "2,4,6",
        "1050 / 2100 /3150",
        "Jaybro Group Pty Ltd",
        "Austroads TCU - DB80 T150S",
        "https://austroads.gov.au/__data/assets/pdf_file/0034/467467/211220-TCU-DB80-T150-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBrefS5WpFUQp3ZChsaGfV0ARIGo-24pC9FegEhfTI9qXk?e=Bo5Jmz",
        "https://cromptonconcepts-my.sharepoint.com/:i:/g/personal/sanju_cromptonconcepts_com_au/IQBGtPXQuQdgRrL70GzZkE3AAeo3r2-aR2ZJysdBIpHnO70?e=8fsU5m",
        "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        "Anchored at ends only",
        null,
        "Max 80 km/h",
        100,
        0.57,
        92,
        0.81,
        2.5,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "DB80A T150S",
        "DB80A T150S Precast Concrete Barrier",
        "MASH TL3 (concrete installation) ",
        "Concrete F-Shape",
        3,
        "M20 x 380mm threaded rod with epoxy ",
        "Max 80 km/h",
        100,
        0.5700000000000001,
        68,
        0.34,
        0.91,
        0.1,
        "2,4,6",
        "1100 /2200 / 3300",
        "Jaybro Group Pty Ltd",
        "Austroads TCU - DB80A T150S",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/533846/221201-TCU-DB80A-T150-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDvXCatzA8nTpYkYrZXiUwzAbDQ2wciURAIYW5_c2VucFA?e=hrndJM",
        "https://cromptonconcepts-my.sharepoint.com/:i:/g/personal/sanju_cromptonconcepts_com_au/IQBGtPXQuQdgRrL70GzZkE3AAeo3r2-aR2ZJysdBIpHnO70?e=hSkvqo",
        "This F shape temporary concrete barrier is only acceptable for use\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        null,
        null,
        "MASH TL3 (asphalt installation) ",
        null,
        3,
        "DB-Pin P600A",
        "Max 80 km/h",
        80,
        0.57,
        68,
        0.55,
        0.91,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "JJ Hooks MASH",
        "JJ Hooks MASH Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Freestanding",
        "NA",
        "Max 80 km/h",
        100,
        0.61,
        59,
        1.63,
        2.23,
        0.06,
        3.6,
        2600,
        "Australian Road Barriers",
        "3.6 Metre Barrier Unit",
        "https://austroads.gov.au/__data/assets/pdf_file/0025/480508/220314-TCU-3.6-M-JJ-Hooks-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBx_780JrG9Q7IgN8KWbkYbAfx86uYATVT3CJnifxiniXg?e=JTjSFr",
        "https://cromptonconcepts-my.sharepoint.com/:i:/g/personal/sanju_cromptonconcepts_com_au/IQDz1S_A7n2HS4ywBfioJj3UAcQ6l2bz9NWREvWOUPFBf9U?e=wvyca2",
        "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        "Freestanding",
        null,
        "Max 80 km/h",
        100,
        0.6,
        66,
        1.6,
        2.2,
        0.06,
        6,
        4430,
        null,
        "6 Metre Barrier Unit",
        "https://austroads.gov.au/__data/assets/pdf_file/0026/480509/220314-TCU-JJ-HOOKS-MASH-Safety-Barrier-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        "T-LOK",
        "T-LOK Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Freestanding",
        "NA",
        "Max 80 km/h",
        100,
        0.6099999999999999,
        58.5,
        1.27,
        1.88,
        0.05,
        "3.6, 5.49",
        "2600, 3900",
        "Saferoads",
        "Austroads TCU - T-LOK",
        "https://austroads.gov.au/__data/assets/pdf_file/0019/570520/230601-TCU-T-LOK-MASH-F-TYPE-Concrete-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDSMh97B_yDQq8gWN6yM8tnAdTb3GbocCIUEYnerwdlTw8?e=wh8Lh2",
        "https://cromptonconcepts-my.sharepoint.com/:i:/g/personal/sanju_cromptonconcepts_com_au/IQCrkOkJ7Gs2SLRCwpYJycVqAfWgW5ik6QxWtvxS439m-SQ?e=A7JTqJ",
        "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.\nThe Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
        null
      ],
      [
        "T-LOK Rubber",
        "T-LOK Rubber Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Freestanding",
        "NA",
        "Max 80 km/h",
        100,
        0.6100000000000001,
        58.5,
        1.76,
        2.37,
        0.05,
        "3.6, 5.49",
        "2600, 3900",
        "Saferoads",
        "Austroads TCU - T-LOK Rubber",
        "https://austroads.gov.au/__data/assets/pdf_file/0020/570521/230601-TCU-T-LOK-Rubber-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBEoZiVSNbgRpBtMU_SZbMzAadu6jK2AP5iKGSehr6MUQI?e=cAefBw",
        null,
        "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.\nThe Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
        null
      ],
      [
        "Pin and Loop",
        "Pin and Loop Precast Concrete Barrier",
        "MASH TL-3",
        "Concrete F-Shape",
        "Freestanding",
        "NA",
        "Max 80 km/h",
        100,
        0.6100000000000001,
        61.4,
        1.61,
        2.22,
        0.07,
        "3.81, ",
        2640,
        "Pin and Loop Pty Ltd",
        "Austroads TCU - Pin and Loop",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/463434/211201-TCU-PIN-and-LOOP-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQC21N5hLheYQ4TgR-0PH1q3AX1op4gn9ItJEd1tK4-l0x4?e=mdSbb7",
        null,
        "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        "BG800",
        "BG800 Steel Rail Safety Barrier",
        "MASH TL-3",
        "Steel",
        60,
        null,
        "Nil",
        100,
        0.5400000000000003,
        72,
        1.66,
        2.2,
        0.08,
        "6, 12",
        "540, 1080",
        "Ingal Civil Products",
        "BG800 Standard - Temporary:",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/463455/211201-TCU-BG800-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAE65BL7aOMQIdrdH-m001nAZwtMqzvsg2iA1lMZMExwOw?e=Yf6VGs",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        60,
        null,
        null,
        100,
        0.54,
        72,
        2.31,
        3.66,
        0.08,
        6,
        540,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "BG800 MDS Steel Safety Barrier",
        "MASH TL-3",
        "Steel",
        6,
        "M24 x 250mm threaded rod with epoxy \n\nM24 x 450mm threaded rod with epoxy ",
        null,
        100,
        0.54,
        42,
        0.44,
        0.98,
        0.08,
        "6, 12",
        "540, 1080",
        null,
        "BG800 MDS - Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0031/463459/211201-TCU-BG800-MDS-Safety-Barrier-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        null,
        "BG800 LDS Steel Safety Barrier",
        "MASH TL-2",
        "Steel",
        12,
        "M24 x 460mm Threaded rod with epoxy ",
        null,
        80,
        0.54,
        72,
        0.42,
        0.96,
        0.08,
        "6, 12",
        "720, 1440",
        null,
        "BG800 LDS - Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/463452/211201-TCU-BG800-LDS-Safety-Barrier-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        "HighwayGuard",
        "HighwayGuard Safety Barrier - Temporary",
        "MASH TL-3",
        "Steel",
        42,
        "figure out later",
        "Nil",
        100,
        0.54,
        108,
        1.71,
        2.25,
        0.08,
        "6, 12",
        "552, 1034",
        "Ingal Civil Products",
        "HighwayGuard Standard - Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/516552/220908-TCU-HIGHWAYGUARD-Safety-Barrier-Temporary.pdf",
        "C:\\Users\\Sanju\\OneDrive - CromptonConcepts\\Desktop\\Temporary barriers\\TMR Approved Barriers\\Barriers\\10.HighwayGuard\\Standard",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        58,
        null,
        null,
        100,
        0.5400000000000003,
        120,
        1.93,
        2.47,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        58,
        null,
        null,
        100,
        1.3499999999999996,
        120,
        2.16,
        3.51,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "HighwayGuard LDS Safety Barrier – Temporary ",
        "MASH TL-3",
        null,
        12,
        "M24 x 330mm threaded rod with epoxy\n(12 metre anchor spacing only) \nM24 x 450mm threaded rod with epoxy ",
        null,
        100,
        0.5399999999999999,
        60,
        0.68,
        1.22,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        "HighwayGuard LDS - Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/463448/211201-TCU-HIGHWAYGUARD-LDS-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQA_UG-EDewmQ7DALi7YAtf8AWoPx6wojO3P2Yz_gDj27AY?e=BUbMke",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        24,
        null,
        null,
        100,
        0.54,
        60,
        1.16,
        1.7,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        24,
        null,
        null,
        100,
        1.72,
        84,
        1.16,
        2.88,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "HighwayGuard MDS Safety Barrier – Temporary ",
        "MASH TL-3",
        null,
        2,
        null,
        null,
        100,
        0.54,
        36,
        0.025,
        0.67,
        0.08,
        "6, 12",
        "552, 1034",
        null,
        "HighwayGuard MDS - Temporary (TL-3):",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/570528/230601-TCU-HIGHWAYGUARD-MDS-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDAh9QlCy3rS6xmAFLvuaJTAZPFCNVu_o5R1ko0NA6B390?e=7lggQa",
        null,
        null,
        null
      ],
      [
        "Defender Barrier",
        "DEFENDER Barrier 70 Steel Safety Barrier - Temporary  ",
        "MASH TL-2",
        "Steel",
        "Freestanding with ballast ",
        null,
        "Nil",
        70,
        0.6799999999999999,
        105,
        1.2,
        1.88,
        0.1,
        3.96,
        320,
        "Safe Barriers Pty. Ltd.",
        "Defender Barrier 70:",
        "https://austroads.gov.au/__data/assets/pdf_file/0028/463429/211201-TCU-DEFENDER-70-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQC0rwROKN1lS6HjYcpuC9CKAQFApKzZkC_5y6LEGwJu9V0?e=cz22ty",
        null,
        null,
        null
      ],
      [
        null,
        "DEFENDER Barrier 100 LDS Safety Barrier - Temporary",
        "MASH TL-3",
        null,
        9.15,
        "Deep lift asphaltic concrete - M25 x 440mm threaded rod with epoxy \n\nAsphaltic concrete over granular pavement - M30 x 500mm asphalt pin ",
        null,
        100,
        0.68,
        78,
        0.88,
        1.56,
        0.1,
        3.96,
        303,
        null,
        "Defender Barrier 100 LDS",
        "https://austroads.gov.au/__data/assets/pdf_file/0022/444307/210903-TCU-DEFENDER-100-LDS-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDt6nwa8K77T53ggK7kWT7rAUWTQjuqqkRmjr1L0xuaKKM?e=1wQ4fx",
        null,
        null,
        null
      ],
      [
        null,
        "DEFENDER Barrier 100 HC Steel Safety Barrier - Temporary ",
        "MASH TL-3",
        null,
        45.45,
        "M30 x 500mm asphalt pin",
        null,
        100,
        0.68,
        97.5,
        1.96,
        2.44,
        0.1,
        3.96,
        303,
        null,
        "Defender Barrier 100 HC:",
        "https://austroads.gov.au/__data/assets/pdf_file/0021/444306/210903-TCU-DEFENDER-100-HC-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAOl0nnSYxXRq8E8wt1l8r-ATNOWUMIkM2myzLODy4EkXY?e=clmuKO",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        48.14,
        "M30 x 500mm asphalt pin",
        null,
        100,
        0.6800000000000002,
        97.5,
        2.3,
        2.98,
        null,
        3.96,
        303,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        48.14,
        "M30 x 500mm asphalt pin",
        null,
        100,
        0.68,
        97.5,
        2.47,
        3.31,
        null,
        3.96,
        303,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "DEFENDER 100 FS Safety Barrier - Temporary ",
        "MASH TL-3",
        null,
        "Freestanding with ballast",
        null,
        null,
        100,
        0.68,
        156,
        1.9,
        2.58,
        0.1,
        3.96,
        320,
        null,
        "Defender Barrier 100 FS",
        "https://austroads.gov.au/__data/assets/pdf_file/0022/463432/211201-TCU-DEFENDER-100-FS-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDoNyGUN-i6RK2LvQf-Oqp6ASeuDNKZYJ2k762fpSw-0-U?e=ao0Wdf",
        null,
        null,
        null
      ],
      [
        "SafeZone",
        "SAFEZONE Safety Barrier - Temporary  ",
        "MASH TL-3",
        "Steel",
        69.6,
        "figure out later",
        "Nil",
        100,
        0.454,
        69.6,
        1.7,
        2.06,
        0.08,
        "5.8,",
        464,
        "Jaybro Group Pty Ltd",
        "SafeZone Standard - Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0013/633100/240307-TCU-SafeZone-LDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCY9H9p7Y-nRZkKtiGYrItzAaaJVrYK7ghOxEX1j5HA9NE?e=LGAV8i",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        69.6,
        null,
        null,
        100,
        0.454,
        69.6,
        2.07,
        2.96,
        0.08,
        "5.8,",
        464,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "SafeZone LDS Safety Barrier – Permanent & Temporary  ",
        "MASH TL-3",
        "Steel",
        11.6,
        "Concrete - M30 x 300mm threaded rod with  epoxy (TL4) or M30 x 175mm threaded rod with  epoxy (TL3 only) \n\nDeep lift asphaltic concrete - M30 x 300mm threaded rod with epoxy\n\nAsphaltic concrete over granular - M30 x 300mm threaded rod with epoxy ",
        null,
        100,
        0.64,
        40.6,
        0.42,
        1.06,
        0.08,
        "5.8, 11.6",
        "464, 1070",
        null,
        "SafeZone LDS – Permanent & Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        11.6,
        null,
        null,
        100,
        0.64,
        40.6,
        0.45,
        2.17,
        0.08,
        "5.8, 11.6",
        "464, 1070",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "SAFEZONE MDS Safety Barrier – Permanent & Temporary ",
        "MASH TL-3",
        "Steel",
        5.8,
        "M30 x 300mm threaded rod with epoxy  ",
        null,
        100,
        0.639,
        40.6,
        0.17,
        0.81,
        0.08,
        5.8,
        464,
        null,
        "SafeZone MDS - Permanent & Temporary",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        "IronMan Hybrid MASH",
        "IRONMAN HYBRID Steel Safety Barrier - Temporary ",
        "MASH TL-2",
        "Steel",
        "freestanding",
        null,
        "Bespoke Wedge ≤60",
        70,
        0.55,
        114.3,
        1.49,
        2.04,
        0.05,
        4.15,
        925,
        "Saferoads",
        "Austroads TCU - IronMan",
        "https://austroads.gov.au/__data/assets/pdf_file/0030/598620/230925-TCU-IRONMAN-HYBRID-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAUrDclLO-OS5y3Q_0KsCaSAe7DXAZufGpgEdJ6uTA_PGw?e=RkCLwe",
        null,
        "The Bespoke Wedge is accepted for use where the speed limit is\nrestricted to 60 km/h or less.",
        null
      ],
      [
        "Zoneguard",
        "ZONEGUARD Steel Safety Barrier - Temporary",
        "MASH TL-3",
        "Steel",
        65,
        "Concrete - M30 x 300mm threaded rod with  epoxy \n\nDeep lift asphaltic concrete, Asphaltic concrete over granular pavement, Flush seal over granular pavement - M30 x 500mm\n\n ",
        "Nil",
        100,
        0.7000000000000002,
        75,
        1.9,
        2.6,
        0.07,
        "4.11, 11.85",
        "400, 1100",
        "Hill & Smith",
        "Zoneguard Standard",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/464981/211208-TCU-ZONEGUARD-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQApkEcGBtuZQpO8utTHqagEAZ-CafBa7wSggd3MVh9vVKY?e=cepeMd",
        null,
        null,
        null
      ],
      [
        null,
        "ZONEGUARD MDS Steel Safety Barrier - Temporary  ",
        "NCHRP 350 TL3 update (Concrete Installation)",
        null,
        10.2,
        "M30 x 300mm treaded rod with epoxy ",
        null,
        100,
        0.7,
        95,
        0.13,
        0.83,
        0.07,
        "4.11, 11.85",
        "400, 1100",
        null,
        "Zoneguard MDS",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/406985/210304-TCU-ZONEGUARD-MDS-Safety-Barrier-Temporary.pdf",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL3 (Asphalt Installation) ",
        null,
        6,
        "M30 x 500mm asphalt pin",
        null,
        100,
        0.7,
        95,
        0.1,
        0.8,
        0.07,
        "4.11, 11.85",
        "400, 1100",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "HV2",
        "HV2 Steel and Concrete Longitudinal Barrier - Temporary",
        "MASH TL-3",
        "Steel",
        "Freestanding with ballast ",
        null,
        "Nil",
        100,
        0.45,
        98.6,
        1.47,
        1.84,
        0.05,
        5.8,
        2088,
        "Saferoads Pty Ltd",
        "Austroads TCU - HV2",
        "https://austroads.gov.au/__data/assets/pdf_file/0021/463440/211201-TCU-HV2-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDPaYppRQs-Q4N6w4ToxD0AAUmqiBVFMe2rXW44JnqyAQ0?e=VzoC14",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        null,
        null,
        null,
        100,
        0.45,
        278,
        2.37,
        3.74,
        0.05,
        5.8,
        2088,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "ArmorZone MASH",
        "ArmorZone MASH Water Filled Safety Barrier System - Temporary",
        "MASH TL-1",
        "Plastic Water Filled",
        "NA",
        null,
        "Nil",
        50,
        0.44999999999999973,
        50,
        2.16,
        2.61,
        0.1,
        2,
        496,
        "Ingal Civil Products",
        "Austroads TCU - ArmorZone",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/388283/201120-TCU-ARMORZONE-MASH-Water-Filled-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCCjrIVJnSPTrg6Xeh8qycbAYvj07xSgU9XVXdUXZk6zW4?e=qA8PLF",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-2",
        null,
        null,
        null,
        null,
        70,
        0.45,
        50,
        4.1,
        4.6,
        0.1,
        2,
        496,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "Ricochet",
        "RICOCHET Plastic Water Filled Safety Barrier System - Temporary",
        "MASH TL-1",
        "Plastic Water Filled",
        "NA",
        null,
        "Nil",
        50,
        0.5800000000000001,
        45,
        2.28,
        2.86,
        0.1,
        2,
        580,
        "TFH Hire Services",
        "Austroads TCU - Ricochet",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/388323/201120-TCU-RICOCHET-Water-Filled-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCYL7MVSYYhSqorgKdBplmbAaiiOw_Zu7OimSb8PN-uS3s?e=dbWrLR",
        null,
        null,
        null
      ],
      [
        "Lo-Ro Water Cable Barrier",
        "Lo-Ro Water Filled Cable Barrier System - Temporary ",
        "MASH TL-1",
        "Plastic Water Filled",
        "freestanding",
        null,
        "Nil",
        50,
        0.57,
        48,
        1.8,
        2.3,
        0.1,
        1.92,
        688,
        "Jaybro Group Pty Ltd",
        "Austroads TCU - Lo-Ro",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/388320/201120-TCU-LO-RO-Water-Cable-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDBHRe_uqT1SaTUiW5-8TXgAUY3Cd-G3-033GQQYHAKgfM?e=YdxyXc",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-2",
        null,
        null,
        null,
        null,
        70,
        0.57,
        48,
        3.6,
        4.1,
        0.1,
        1.92,
        688,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "Shield I",
        "SHIELD I Water Filled Safety Barrier System - Temporary ",
        "MASH TL-1",
        "Plastic Water Filled",
        "freestanding",
        null,
        "Nil",
        50,
        0.5999999999999996,
        52,
        2.2,
        2.8,
        0.05,
        2.2,
        611,
        "National Plastic Group",
        "Austroads TCU - Shield I",
        "https://austroads.gov.au/__data/assets/pdf_file/0030/388326/201120-TCU-SHIELD-I-Water-Filled-Barrier-System-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAUlEQKQuqoRLf5dV8UKo3mASE0hqnt51jV83jCgKmOW48?e=ovOaTx",
        null,
        null,
        null
      ],
      [
        "Mobile Barriers MBT-1",
        "MOBILE BARRIER MBT-1 Steel Safety Barrier - Temporary ",
        "MASH TL-3",
        "Mobile Workzone",
        "NA",
        null,
        "Nil",
        80,
        0.61,
        30.5,
        0.61,
        1.22,
        0.07,
        "12.8, 18.9",
        "9000, 38500",
        "Mobile Barriers",
        "Austroads TCU - MBT-1",
        "https://austroads.gov.au/__data/assets/pdf_file/0025/388321/201120-TCU-MBT-1-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQB0uDBf3CfbSq_pKXPdKmxGAe_Vr_sFAt7teAATep4EBXs?e=s3AcBT",
        null,
        null,
        null
      ],
      [
        "Rebloc 80SAH 12",
        "Rebloc 80SAH_12 Safety Barrier - Temporary",
        "MASH TL-3",
        "Concrete Freestanding",
        "Anchored at ends only",
        null,
        "Nil",
        100,
        0.3,
        108,
        1.31,
        1.56,
        0.1,
        12,
        3270,
        "Onsite",
        "Austroads TCU - Rebloc",
        "https://austroads.gov.au/__data/assets/pdf_file/0015/515130/220902-TCU-Rebloc-80SAH_12-Safety-Barrier.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBo1kWy6NGIRIqpHr0YuBNmATrUAk05BLBaO894fcDOhOs?e=w4E3p7",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-4",
        null,
        null,
        null,
        null,
        100,
        0.3,
        156,
        1.7,
        3.23,
        0.1,
        12,
        3270,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "Rebloc 80SAH 12 8B",
        "Rebloc 80SAH_12_8B Safety Barrier - Temporary",
        "MASH TL-3",
        "Concrete Anchored",
        4,
        "HSB 20 x 300mm screw bolt ",
        "Nil",
        100,
        0.3,
        60,
        0.3,
        0.6,
        0.1,
        12,
        3270,
        "Onsite",
        "Austroads TCU - Rebloc",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/481626/220322-TCU-Rebloc-80SAH_12_8B-Safety-Barrier.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAcpNHmM849T70d96I491reAb1vlu6zPHpufYYmS4tPe_k?e=EfYwb3",
        null,
        null,
        null
      ],
      [
        "Rebloc 80SAH 4",
        "Rebloc 80SAH_4 Safety Barrier - Temporary ",
        "MASH TL-3 ",
        "Concrete Freestanding",
        "Anchored at ends only",
        null,
        "Nil",
        100,
        0.30000000000000004,
        109,
        1.21,
        1.51,
        0.1,
        4.03,
        1110,
        "Onsite",
        "Austroads TCU - Rebloc",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/533576/221201-TCU-Rebloc-80SAH_4-Safety-Barrier-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBd_vnDEaZrQaldcLgSRgjJASTTZxhPlQiMwRa8t0ZkiuU?e=U6iReN",
        null,
        null,
        null
      ],
      [
        "Rebloc 120FA 6 SF",
        "Rebloc 120FA_6_SF Safety Barrier - Temporary",
        "MASH TL-3",
        "Concrete Freestanding",
        "Anchored at ends only",
        null,
        "Max 80 km/h",
        100,
        0.62,
        102,
        0.4,
        1,
        0.1,
        6,
        4780,
        "Onsite",
        "Austroads TCU - Rebloc",
        "https://austroads.gov.au/__data/assets/pdf_file/0043/498778/220616-TCU-Rebloc-120FA_6_FS-Safety-Barrier.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDRmAouByW9Qq4SHyvIt2S5ATqUzZA4UN6IQfozqa7TIyA?e=2m6LVV",
        null,
        "This F shape temporary concrete barrier is acceptable for use only\non roads with speed limits of 80 km/h or less.",
        null
      ],
      [
        null,
        null,
        "MASH TL-5",
        null,
        null,
        null,
        null,
        null,
        0.62,
        102,
        1.58,
        2.29,
        0.1,
        6,
        4780,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "Sheet1": [
      [
        "Barrier System",
        "Image Link",
        "Austroads TCU Link",
        "Recommended End treatments",
        "Manufacturers Specifications"
      ],
      [
        "Precast Concrete Barrier (PCB)",
        null,
        null,
        null,
        null
      ],
      [
        "DB80 K150 Precast Concrete Barrier",
        "https://www.rsea.com.au/Images/ProductImages/Medium/DB80_1.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0018/433206/210720-TCU-DB80-K150-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDX7trjrgYoSJsV4jJPnx4PAbdOzJasBl5HFtl9VxgNDE4?e=G5cE0F"
      ],
      [
        "DB80 T150S Precast Concrete Barrier",
        "https://deltabloc.com/assets/images/9/slider-db80-product-01-d5f86934.webp",
        "https://austroads.gov.au/__data/assets/pdf_file/0034/467467/211220-TCU-DB80-T150-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBrefS5WpFUQp3ZChsaGfV0ARIGo-24pC9FegEhfTI9qXk?e=Bo5Jmz"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "DB80A T150S Precast Concrete Barrier",
        "https://deltabloc.com/assets/images/9/slider-db80-product-01-d5f86934.webp",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/533846/221201-TCU-DB80A-T150-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDvXCatzA8nTpYkYrZXiUwzAbDQ2wciURAIYW5_c2VucFA?e=hrndJM"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "JJ Hooks MASH Precast Concrete Barrier",
        "https://s.yimg.com/ny/api/res/1.2/UlYB4Dh.4B0CAJsf4YWd5w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTM0MA--/https://media.zenfs.com/en/accesswire.ca/23c1b596b6abd4fe4b9e65c0db6631f9",
        "https://austroads.gov.au/__data/assets/pdf_file/0025/480508/220314-TCU-3.6-M-JJ-Hooks-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBx_780JrG9Q7IgN8KWbkYbAfx86uYATVT3CJnifxiniXg?e=JTjSFr"
      ],
      [
        null,
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0026/480509/220314-TCU-JJ-HOOKS-MASH-Safety-Barrier-Temporary.pdf",
        null,
        null
      ],
      [
        "T-LOK Precast Concrete Barrier",
        "https://www.rockinghamprecast.com/assets/barrier/Barrier-1-1024x682-e95d03ae3260558bf15e2099b35e70a1e313f215f9b847ccb799794663fe98ff.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0019/570520/230601-TCU-T-LOK-MASH-F-TYPE-Concrete-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDSMh97B_yDQq8gWN6yM8tnAdTb3GbocCIUEYnerwdlTw8?e=wh8Lh2"
      ],
      [
        "T-LOK Rubber Precast Concrete Barrier",
        "https://www.saferoads.com.au/media/rubbertlok1472.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0020/570521/230601-TCU-T-LOK-Rubber-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBEoZiVSNbgRpBtMU_SZbMzAadu6jK2AP5iKGSehr6MUQI?e=cAefBw"
      ],
      [
        "Pin and Loop Precast Concrete Barrier",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd_vcY9htRDEx3kmmIPL8e_dFsQ77E7J1cmA&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/463434/211201-TCU-PIN-and-LOOP-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQC21N5hLheYQ4TgR-0PH1q3AX1op4gn9ItJEd1tK4-l0x4?e=mdSbb7"
      ],
      [
        "BG800 Steel Rail Safety Barrier",
        "https://webassetsprod.valmont.com/valmontproduction/images/ingalcivilau2024libraries/products/guardrail/ezyguard-smart/ezyguard-smart.png?sfvrsn=63618039_1",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/463455/211201-TCU-BG800-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAE65BL7aOMQIdrdH-m001nAZwtMqzvsg2iA1lMZMExwOw?e=Yf6VGs"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "BG800 MDS Steel Safety Barrier",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0031/463459/211201-TCU-BG800-MDS-Safety-Barrier-Temporary.pdf",
        null,
        null
      ],
      [
        "BG800 LDS Steel Safety Barrier",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0024/463452/211201-TCU-BG800-LDS-Safety-Barrier-Temporary.pdf",
        null,
        null
      ],
      [
        "HighwayGuard Safety Barrier - Temporary",
        "https://www.rpmhire.com.au/wp-content/uploads/2022/09/38-1-1024x1024.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/516552/220908-TCU-HIGHWAYGUARD-Safety-Barrier-Temporary.pdf",
        null,
        "C:\\Users\\Sanju\\OneDrive - CromptonConcepts\\Desktop\\Temporary barriers\\TMR Approved Barriers\\Barriers\\10.HighwayGuard\\Standard"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "HighwayGuard LDS Safety Barrier – Temporary ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0029/463448/211201-TCU-HIGHWAYGUARD-LDS-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQA_UG-EDewmQ7DALi7YAtf8AWoPx6wojO3P2Yz_gDj27AY?e=BUbMke"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "HighwayGuard MDS Safety Barrier – Temporary ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0027/570528/230601-TCU-HIGHWAYGUARD-MDS-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDAh9QlCy3rS6xmAFLvuaJTAZPFCNVu_o5R1ko0NA6B390?e=7lggQa"
      ],
      [
        "DEFENDER Barrier 70 Steel Safety Barrier - Temporary  ",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMm5AdBQwuyp-njndvqUyd9L2girh5J469fw&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0028/463429/211201-TCU-DEFENDER-70-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQC0rwROKN1lS6HjYcpuC9CKAQFApKzZkC_5y6LEGwJu9V0?e=cz22ty"
      ],
      [
        "DEFENDER Barrier 100 LDS Safety Barrier - Temporary",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0022/444307/210903-TCU-DEFENDER-100-LDS-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDt6nwa8K77T53ggK7kWT7rAUWTQjuqqkRmjr1L0xuaKKM?e=1wQ4fx"
      ],
      [
        "DEFENDER Barrier 100 HC Steel Safety Barrier - Temporary ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0021/444306/210903-TCU-DEFENDER-100-HC-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAOl0nnSYxXRq8E8wt1l8r-ATNOWUMIkM2myzLODy4EkXY?e=clmuKO"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "DEFENDER 100 FS Safety Barrier - Temporary ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0022/463432/211201-TCU-DEFENDER-100-FS-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDoNyGUN-i6RK2LvQf-Oqp6ASeuDNKZYJ2k762fpSw-0-U?e=ao0Wdf"
      ],
      [
        "SAFEZONE Safety Barrier - Temporary  ",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrke7EEFUMwI0AfwPZuWn2eWlrr_H3L95STw&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0013/633100/240307-TCU-SafeZone-LDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCY9H9p7Y-nRZkKtiGYrItzAaaJVrYK7ghOxEX1j5HA9NE?e=LGAV8i"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "SafeZone LDS Safety Barrier – Permanent & Temporary  ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "SAFEZONE MDS Safety Barrier – Permanent & Temporary ",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0029/592643/230901-TCU-SAFEZONE-MDS-Safety-Barrier-Permanent-and-Temporary.pdf",
        null,
        null
      ],
      [
        "IRONMAN HYBRID Steel Safety Barrier - Temporary ",
        "https://www.saferoads.com.au/media/IHB-2.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0030/598620/230925-TCU-IRONMAN-HYBRID-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAUrDclLO-OS5y3Q_0KsCaSAe7DXAZufGpgEdJ6uTA_PGw?e=RkCLwe"
      ],
      [
        "ZONEGUARD Steel Safety Barrier - Temporary",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0032/464981/211208-TCU-ZONEGUARD-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQApkEcGBtuZQpO8utTHqagEAZ-CafBa7wSggd3MVh9vVKY?e=cepeMd"
      ],
      [
        "ZONEGUARD MDS Steel Safety Barrier - Temporary  ",
        "https://hillandsmith.com/wp-content/uploads/2022/02/floating-image.png",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/406985/210304-TCU-ZONEGUARD-MDS-Safety-Barrier-Temporary.pdf",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "HV2 Steel and Concrete Longitudinal Barrier - Temporary",
        null,
        "https://austroads.gov.au/__data/assets/pdf_file/0021/463440/211201-TCU-HV2-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDPaYppRQs-Q4N6w4ToxD0AAUmqiBVFMe2rXW44JnqyAQ0?e=VzoC14"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "ArmorZone MASH Water Filled Safety Barrier System - Temporary",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqvX9uI5h7NpJSrwBs6d28iMU3GQysQGj1kQ&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/388283/201120-TCU-ARMORZONE-MASH-Water-Filled-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCCjrIVJnSPTrg6Xeh8qycbAYvj07xSgU9XVXdUXZk6zW4?e=qA8PLF"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "RICOCHET Plastic Water Filled Safety Barrier System - Temporary",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlYEbeYaI4LAckOZhO2SSIHaEw3Mx2QQ8-Sg&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/388323/201120-TCU-RICOCHET-Water-Filled-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCYL7MVSYYhSqorgKdBplmbAaiiOw_Zu7OimSb8PN-uS3s?e=dbWrLR"
      ],
      [
        "Lo-Ro Water Filled Cable Barrier System - Temporary ",
        "https://www.jaybro.com.au/pub/media/catalog/product/1/5/15-loror-lo-ro-water-cable-barrier-red.jpg?width=265&height=265&store=au_default&image-type=image",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/388320/201120-TCU-LO-RO-Water-Cable-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDBHRe_uqT1SaTUiW5-8TXgAUY3Cd-G3-033GQQYHAKgfM?e=YdxyXc"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "SHIELD I Water Filled Safety Barrier System - Temporary ",
        "https://sitehq-production.s3.amazonaws.com/wp-prod/uploads/5.-Shield-I-Product-Manual1.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0030/388326/201120-TCU-SHIELD-I-Water-Filled-Barrier-System-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAUlEQKQuqoRLf5dV8UKo3mASE0hqnt51jV83jCgKmOW48?e=ovOaTx"
      ],
      [
        "MOBILE BARRIER MBT-1 Steel Safety Barrier - Temporary ",
        "https://www.mobilebarriers.com/media/index_media/Capital%20Beltway%20I-495%20Express%20Lanes%20Maintenance%20_27_n%20Mobile%20Barriers%20MBT-1.jpg",
        "https://austroads.gov.au/__data/assets/pdf_file/0025/388321/201120-TCU-MBT-1-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQB0uDBf3CfbSq_pKXPdKmxGAe_Vr_sFAt7teAATep4EBXs?e=s3AcBT"
      ],
      [
        "Rebloc 80SAH_12 Safety Barrier - Temporary",
        "https://www.roadsidepooledfund.org/wp-content/uploads/2021/10/Screenshot-153.png",
        "https://austroads.gov.au/__data/assets/pdf_file/0015/515130/220902-TCU-Rebloc-80SAH_12-Safety-Barrier.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBo1kWy6NGIRIqpHr0YuBNmATrUAk05BLBaO894fcDOhOs?e=w4E3p7"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ],
      [
        "Rebloc 80SAH_12_8B Safety Barrier - Temporary",
        "https://www.roadsidepooledfund.org/wp-content/uploads/2021/10/Screenshot-155.png",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/481626/220322-TCU-Rebloc-80SAH_12_8B-Safety-Barrier.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAcpNHmM849T70d96I491reAb1vlu6zPHpufYYmS4tPe_k?e=EfYwb3"
      ],
      [
        "Rebloc 80SAH_4 Safety Barrier - Temporary ",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWHQk1XrRCxX6lrEyVsGFPmr32B-Ttmr-XAA&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/533576/221201-TCU-Rebloc-80SAH_4-Safety-Barrier-Temporary.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBd_vnDEaZrQaldcLgSRgjJASTTZxhPlQiMwRa8t0ZkiuU?e=U6iReN"
      ],
      [
        "Rebloc 120FA_6_SF Safety Barrier - Temporary",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnyqAAIEOlYEDSkUpm3aRalO_m6tWQqLkasQ&s",
        "https://austroads.gov.au/__data/assets/pdf_file/0043/498778/220616-TCU-Rebloc-120FA_6_FS-Safety-Barrier.pdf",
        null,
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDRmAouByW9Qq4SHyvIt2S5ATqUzZA4UN6IQfozqa7TIyA?e=2m6LVV"
      ],
      [
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "Sheet4": [
      [
        "Barrier System",
        "Manufacturer's Specifications Link"
      ],
      [
        "DB80 Series",
        "https://www.jaybro.com.au/eco-barrier"
      ],
      [
        "JJ Hooks MASH",
        "https://www.australianroadbarriers.com.au/products/jj-hooks-mash/"
      ],
      [
        "T-LOK",
        "https://www.saferoads.com.au/products/barriers/temporary-barriers/t-lok"
      ],
      [
        "Pin and Loop",
        "https://pinandloop.com.au/"
      ],
      [
        "BG800",
        "https://www.ingalcivil.com.au/products/temporary-barriers/bg800"
      ],
      [
        "HighwayGuard",
        "https://www.ingalcivil.com.au/products/aus/highwayguard"
      ],
      [
        "Defender Barrier",
        "https://safebarriers.com/defender-barrier/"
      ],
      [
        "SafeZone",
        "https://www.jaybro.com.au/safezone-steel-barrier.html"
      ],
      [
        "IronMan Hybrid",
        "https://www.saferoads.com.au/ironman-hybrid-barrier"
      ],
      [
        "Zoneguard",
        "https://www.rsea.com.au/hire-range/zoneguard"
      ],
      [
        "HV2",
        "https://www.saferoads.com.au/products/barriers/temporary-barriers/hv2-barrier"
      ],
      [
        "ArmorZone MASH",
        "https://www.ingalcivil.com.au/products/temporary-barriers/armorzone-mash-tl-2-tl-3"
      ],
      [
        "Ricochet",
        "https://www.advantageplastics.com.au/ricochet-barrier"
      ],
      [
        "Lo-Ro Water Cable",
        "https://www.jaybro.com.au/lo-ro-water-filled-barrier.html"
      ],
      [
        "Shield I",
        "https://www.barriersystemsinc.com/shield-1-barrier"
      ],
      [
        "Mobile Barriers MBT-1",
        "https://mobilebarriers.com/"
      ],
      [
        "Rebloc",
        "https://www.rebloc.com/en/products/temporary-barriers/"
      ]
    ],
    "End treatment": [
      [
        "End Treatment System",
        "Product Name",
        "Accepted Test Level",
        "Type",
        "Anchor/Post Spacing (m)",
        "Post/Pin Type",
        "TMR Conditions (Speed)",
        "Test Speed (km/h)",
        "Width of system (m)",
        "Tested Article Length (m) ",
        "Deflection (m)",
        "Working Width (m)",
        "Side slope limit",
        "Registered Supplier",
        "Austroads TCU Link",
        "Manufacturers Specifications",
        "TMR Conditions"
      ],
      [
        "Absorb-M",
        "Absorb-M Plastic Crash Cushion",
        "MASH TL-2 ",
        "Water Filled, Non-Redirective, Gating Plastic Terminal",
        "Freestanding",
        "N/A",
        "Max 60 km/h ",
        60,
        0.67,
        5.29,
        "N/A (Gating)",
        "N/A",
        0.1,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0031/425587/210607-TCU-ABSORB-M-Crash-Cushion.pdf",
        "https://www.safedirection.com.au/wp-content/uploads/2023/04/Installation-Manual-ABSORB-M-Plastic-Crash-Cushion.pdf",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        null,
        null,
        "Max 80 km/h ",
        80,
        0.67,
        7.22,
        null,
        null,
        0.1,
        null,
        null,
        null,
        null
      ],
      [
        "ArmorBuffa",
        "ArmorBuffa Plastic Water Filled Crash Cushion",
        "MASH TL-3",
        "Non-Redirective, Gating Plastic Water Filled End Treatment",
        "Freestanding",
        "N/A",
        "Max 80 km/h (TL-3)",
        80,
        0.46,
        9.313,
        "N/A (Gating)",
        "N/A",
        0.1,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/444291/210903-TCU-ArmorBuffa-Crash-Cushion.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQDEqXg2DbbER7nbMQOmucU3ASGynthJt4VmZeU5o7xyWM0?e=GekvdR",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-2",
        null,
        null,
        null,
        "Max 70 km/h (TL-2)",
        70,
        0.46,
        5.31,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "SLED",
        "SLED Plastic Water Filled End Terminal",
        "MASH TL-1",
        "Non-Redirective, Gating Plastic Water Filled End Treatment",
        "Freestanding",
        "N/A",
        "Max 50 km/h (TL-1)",
        50,
        0.7,
        3.85,
        "N/A (Gating)",
        "N/A",
        0.1,
        "Saferoads Pty Ltd",
        "https://austroads.gov.au/__data/assets/pdf_file/0022/391261/201205-TCU-SLED-Water-Filled-End-Terminal.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCP_v2guPR2TYw9AkEMYkheAbqZkdYza4JdXJYXq3GbKfA?e=pugMV0",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-2",
        null,
        null,
        null,
        "Max 70 km/h (TL-2)",
        70,
        0.7,
        5.77,
        "N/A (Gating)",
        "N/A",
        0.1,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        null,
        null,
        "Max 80 km/h (TL-3)",
        80,
        0.7,
        7.92,
        "N/A (Gating)",
        "N/A",
        0.1,
        null,
        null,
        null,
        null
      ],
      [
        "Universal TAU-M",
        "Universal TAU-M Crash Cushion",
        "MASH TL-2 ",
        "Redirective Crash Cushion",
        "Refer to Drawings",
        "Refer to Drawings",
        70,
        70,
        0.76,
        4.33,
        "Redirective",
        "Redirective",
        0.08,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0029/633386/240307-TCU-Universal-Tau-M-Crash-Cushion-Permanent-and-Temporary.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCwlwNu2L9JRbZkC8TRVcJnAeOMbdn28Bb27bhmY39k9qY?e=U0jf5j",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        "Redirective Crash Cushion",
        null,
        null,
        100,
        100,
        0.76,
        6.93,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "TAU-XR",
        "TAU-XR Crash Cushion",
        "MASH TL-3",
        "Redirective Crash Cushion",
        "Refer to Drawings",
        "Refer to Drawings",
        "100 km/h",
        100,
        0.91,
        7.18,
        "Redirective",
        "Redirective",
        0.08,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/674910/240904-TCU-Tau-XR-Crash-Cushion.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAn6_jgye_5T7RNJ4LLfKxGAcaHWobIra_UQb_Ycy8za9U?e=xA2Wm1",
        "Nil."
      ],
      [
        "ET-SS",
        "ET-SS Guardrail End Terminal",
        "MASH TL-2 ",
        "Gating Terminal",
        1.905,
        "Driven or Baseplate",
        "70 km/h",
        70,
        0.45,
        7.9,
        "Gating",
        "Gating",
        0.1,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/533849/221201-TCU-ET-SS-Terminal.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQA6nEye2kntQoZ-80m2l1CFAQ2nzK4t-IiFP5ff_bgPGCA?e=cmIexp",
        "Refer to TCU."
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        1.905,
        null,
        "100 km/h",
        100,
        0.45,
        15.48,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "MSKT",
        "MASH Sequential Kinking Terminal (MSKT)",
        "MASH TL-2",
        "Gating Terminal",
        1.905,
        "Driven",
        70,
        70,
        0.51,
        9.5,
        "Gating",
        "Gating",
        0.1,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0027/633375/240307-TCU-MSKT-Permanent.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCTf7W7pDUmQpaBDD396tKDAWI80MBWyEYku4__dNwThc0?e=IO4ZgI",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        1.905,
        null,
        100,
        100,
        0.51,
        14.29,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "MAX-Tension",
        "MAX-Tension Guardrail Terminal",
        "MASH TL-2",
        "Gating Terminal",
        1.905,
        "Driven or Baseplate",
        70,
        70,
        0.44,
        9.12,
        "Gating",
        "Gating",
        0.07,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/388247/201120-TCU-MAX-TENSION-Terminal.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQBrv5e3N-VQRqhzZrdg9_1nAVA0wsyHNS4Jr3VCyJR1A2o?e=UTkK3j",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        1.905,
        null,
        100,
        100,
        0.44,
        16.77,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        "Trend Median Terminal",
        "Trend Median Terminal",
        "MASH TL-3",
        "Gating Terminal (Median)",
        1.905,
        "Driven",
        "100 km/h",
        100,
        0.73,
        11.1,
        "Gating",
        "Gating",
        0.1,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/554855/230324-TCU-Trend-Median-Terminal.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQCDUGRch_3uRbx9LFPDkV3JAaQNsEo2wug3KV8_9JrKvJM?e=UVPWCc",
        "Nil."
      ],
      [
        "QUADGUARD M10",
        "QuadGuard M10 Crash Cushion",
        "MASH TL-2",
        "Redirective Crash Cushion",
        "N/A",
        "Refer to Drawings",
        70,
        70,
        0.61,
        4,
        "Redirective",
        "Redirective",
        0.08,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0032/406958/210304-TCU-QUADGUARD-M10-Crash-Cushion.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQAWt9Uq2ojLRbn9iVwWfUfnAanCjD-wUAuURfQVkSS4u3s?e=lU0wsE",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        null,
        "Refer to Drawings",
        100,
        100,
        1.755,
        6.71,
        "Redirective",
        "Redirective",
        0.08,
        null,
        null,
        null,
        null
      ],
      [
        "QUADGUARD M10 CZ",
        "QUADGUARD M10 CZ Crash Cushion",
        "MASH TL-2",
        "Redirective Crash Cushion",
        null,
        "Refer to Drawings",
        70,
        70,
        0.61,
        4,
        "Redirective",
        "Redirective",
        0.08,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0019/444331/210906-TCU-QUADGUARD-M10-CZ-Crash-Cushion.pdf",
        "https://cromptonconcepts-my.sharepoint.com/:b:/g/personal/sanju_cromptonconcepts_com_au/IQACRnHoflQHTb8sUF12d-GdAYDwWI7-69VwA9LBHlYWs3M?e=gPJgqN",
        null
      ],
      [
        null,
        null,
        "MASH TL-3",
        null,
        null,
        "Refer to Drawings",
        100,
        100,
        0.61,
        6.71,
        "Redirective",
        "Redirective",
        null,
        null,
        null,
        null,
        null
      ],
      [
        "QUADGUARD Elite M10",
        "QuadGuard Elite M10 Crash Cushion",
        "MASH TL-3",
        "Redirective Crash Cushion",
        "N/A",
        "Anchored",
        100,
        100,
        "0.61 (Standard) / 1.75 (Wide)",
        8.3,
        "Redirective",
        "Redirective",
        0.08,
        "Ingal Civil Products",
        "https://austroads.gov.au/__data/assets/pdf_file/0030/633378/240307-TCU-Quadguard-Elite-M10-Crash-Cushion-Permanent.pdf",
        "https://www.ingalcivil.com.au/products/aus/quadguard-elite-m10",
        "Nil."
      ],
      [
        "Smart Cushion",
        "Smart Cushion SCI100GM",
        "MASH TL-2",
        "Redirective Crash Cushion",
        "N/A",
        "Anchored",
        70,
        70,
        0.61,
        4.2,
        "Redirective",
        "Redirective",
        0.08,
        "LB Australia",
        "https://austroads.gov.au/__data/assets/pdf_file/0024/391236/201205-TCU-SMART-Steel-Crash-Cushion.pdf",
        "https://lbaustralia.com.au/products/smart-cushion-speed-dependent-crash-attenuator/",
        "Nil."
      ],
      [
        null,
        null,
        "MASH TL-3",
        "Redirective Crash Cushion",
        "N/A",
        "Anchored",
        100,
        100,
        0.61,
        6.6,
        "Redirective",
        "Redirective",
        0.08,
        null,
        null,
        null,
        null
      ],
      [
        "Hercules",
        "Hercules Crash Cushion",
        "MASH TL-3",
        "Redirective Crash Cushion",
        "N/A",
        "Anchored",
        "100 km/h",
        100,
        0.59,
        5.83,
        "Redirective",
        "Redirective",
        0.08,
        "Safe Direction",
        "https://austroads.gov.au/__data/assets/pdf_file/0022/444289/210903-TCU-Hercules-Crash-Cushion.pdf",
        "https://www.safedirection.com.au/products/guardrail-products/road-barriers/crash-cushions/hercules/",
        "Nil."
      ]
    ]
  }
};
